apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sproj
  namespace: vishnu
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    app: myapp
  template:
    metadata:
      name: k8sproj
      labels:
        app: myapp
    spec:
      containers:
        - name: mycont
          image: pranai123/k8sdemoargocd:appimage
          ports:
            - containerPort: 80
          resources:
            requets:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
          imagePullSecrets:
          # kubectl create ns vishnu
          # kubectl create secret docker-registry mysecret --docker-username=pranai123 --docker-password=Pranai@123 -n vishnu
          # Execute the above cmds in KOPS, hence for Docker private repo
            - name: mysecret # Name of the secret
