apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  labels:
    app: myapp
  namespace: vishnu
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80