apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: vishnu
  labels:
    app: dbapp
spec:
  serviceName: "mysqldb" # Links DB pods with DB service
  replicas: 2
  selector:
    matchLabels:
      app: dbapp
  template:
    metadata:
      name: mysql
      labels:
        app: dbapp
    spec:
      containers:
        - name: mydbcont
          image: pranai123/k8sdemoargocd:dbimage
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      imagePullSecrets:
        - name: mysecret
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
