apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: dbapp
  namespace: vishnu
spec:
  clusterIP: None
  selector:
    app: dbapp
  ports:
    - port: 3306
      targetPort: 3306